color = "Always"
edition = "2021"
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_layout = "Vertical"
imports_granularity = "Crate"
match_arm_blocks = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_modules = true
struct_field_align_threshold = 20
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
