[package]
name = "voice-channel-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["time", "env-filter"] }
